apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: my-namespace  # Change this to your namespace
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # Change to LoadBalancer or NodePort if external access is needed
